# Generated by Django 5.2.15 on 2026-06-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='cctv_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residence',
            name='constituency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='residence',
            name='fibre_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residence',
            name='gated_community',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residence',
            name='nearby_hospital',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='residence',
            name='nearby_school',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='residence',
            name='nearest_stage',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='residence',
            name='plot_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='residence',
            name='security_guard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residence',
            name='ward',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='residence',
            name='water_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='residence',
            name='sub_county',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
