# Generated by Django 5.2.15 on 2026-06-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_residence_cctv_available_residence_constituency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='residences/fronts/'),
        ),
        migrations.AddField(
            model_name='residence',
            name='vacancy_poster',
            field=models.ImageField(blank=True, null=True, upload_to='residences/posters/'),
        ),
    ]
