# Generated by Django 5.2.15 on 2026-06-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_residence_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='house_type',
            field=models.CharField(choices=[('single_room', 'Single Room'), ('bedsitter', 'Bedsitter'), ('one_bedroom', 'One Bedroom'), ('two_bedroom', 'Two Bedroom'), ('three_bedroom', 'Three Bedroom'), ('studio', 'Studio')], default='bedsitter', max_length=50),
        ),
    ]
