# Generated by Django 5.2.15 on 2026-06-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
