# Generated by Django 6.0.6 on 2026-06-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_favorite_id_alter_residence_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='house_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Bedsitter', 'Bedsitter'), ('Double Room', 'Double Room'), ('Studio', 'Studio'), ('1 Bedroom', '1 Bedroom'), ('2 Bedroom', '2 Bedroom'), ('3 Bedroom', '3 Bedroom')], default='bedsitter', max_length=50),
        ),
    ]
