# Generated by Django 6.0.6 on 2026-06-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_residence_house_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='house_type',
            field=models.CharField(choices=[('single', 'Single'), ('bedsitter', 'Bedsitter'), ('double_room', 'Double Room'), ('studio', 'Studio'), ('1_bedroom', '1 Bedroom'), ('2_bedroom', '2 Bedroom'), ('3_bedroom', '3 Bedroom')], default='bedsitter', max_length=50),
        ),
    ]
