# Generated by Django 6.0.6 on 2026-06-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_residence_house_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residence',
            name='constituency',
        ),
        migrations.RemoveField(
            model_name='residence',
            name='estate',
        ),
        migrations.RemoveField(
            model_name='residence',
            name='sub_county',
        ),
        migrations.RemoveField(
            model_name='residence',
            name='ward',
        ),
        migrations.AddField(
            model_name='residence',
            name='town',
            field=models.CharField(default='Unknown', help_text='Example: Kasarani, Ruiru, Kitengela', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='residence',
            name='county',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Kiambu', 'Kiambu'), ('Machakos', 'Machakos'), ('Kajiado', 'Kajiado'), ('Muranga', "Murang'a"), ('Nakuru', 'Nakuru'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Uasin Gishu', 'Uasin Gishu')], max_length=100),
        ),
    ]
