# Generated by Django 6.0.6 on 2026-06-29 12:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencephoto',
            name='image',
            field=models.ImageField(upload_to='residences/', validators=[core.models.validate_image]),
        ),
    ]
