# Generated by Django 6.0.6 on 2026-07-02 10:17

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_residencephoto_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencephoto',
            name='image',
            field=models.ImageField(upload_to='residence_photos/', validators=[core.models.validate_image]),
        ),
        migrations.CreateModel(
            name='LeaseAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_full_name', models.CharField(max_length=200)),
                ('tenant_id_number', models.CharField(max_length=50)),
                ('tenant_phone', models.CharField(max_length=20)),
                ('landlord_full_name', models.CharField(max_length=200)),
                ('landlord_phone', models.CharField(max_length=20)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lease_start_date', models.DateField()),
                ('lease_duration_months', models.PositiveIntegerField(default=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='core.residence')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases_as_tenant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
