# Generated by Django 6.0.6 on 2026-07-02 12:23

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_residencephoto_image_leaseagreement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencephoto',
            name='image',
            field=models.ImageField(upload_to='residence_photos/', validators=[core.models.validate_image]),
        ),
        migrations.CreateModel(
            name='RoommateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preferred_county', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Kiambu', 'Kiambu'), ('Machakos', 'Machakos'), ('Kajiado', 'Kajiado'), ('Muranga', "Murang'a"), ('Nakuru', 'Nakuru'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Uasin Gishu', 'Uasin Gishu')], max_length=100)),
                ('preferred_town', models.CharField(blank=True, help_text='Example: Kasarani, Ruiru', max_length=100)),
                ('move_in_timeline', models.CharField(choices=[('immediately', 'Immediately'), ('1_month', 'Within 1 month'), ('flexible', 'Flexible')], default='flexible', max_length=20)),
                ('bio', models.TextField(help_text='Tell others about yourself, habits, work schedule, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
