# Generated by Django 6.0.6 on 2026-07-03 14:37

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_donation_alter_residencephoto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='residencephoto',
            name='image',
            field=models.ImageField(upload_to='residence_photos/', validators=[core.models.validate_image]),
        ),
    ]
