# Generated by Django 6.0.6 on 2026-07-03 14:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_residence_deposit_amount_alter_residencephoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='house_type',
            field=models.CharField(blank=True, help_text='Comma-separated house types available in this residence', max_length=200),
        ),
        migrations.AlterField(
            model_name='residencephoto',
            name='image',
            field=models.ImageField(upload_to='residence_photos/', validators=[core.models.validate_image]),
        ),
    ]
