# Generated by Django 5.0.14 on 2026-07-03 18:42

import core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_residence_house_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewed_residences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='residence',
            name='house_type',
            field=models.CharField(choices=[('single', 'Single'), ('bedsitter', 'Bedsitter'), ('double_room', 'Double Room'), ('studio', 'Studio'), ('1_bedroom', '1 Bedroom'), ('2_bedroom', '2 Bedroom'), ('3_bedroom', '3 Bedroom'), ('single_bedsitter', 'Single & Bedsitter'), ('bedsitter_double', 'Bedsitter & Double Room'), ('bedsitter_studio', 'Bedsitter & Studio'), ('bedsitter_1bed', 'Bedsitter & 1 Bedroom'), ('bedsitter_1bed_2bed', 'Bedsitter, 1 & 2 Bedroom'), ('1bed_2bed', '1 & 2 Bedroom'), ('2bed_3bed', '2 & 3 Bedroom')], default='bedsitter', max_length=50),
        ),
        migrations.AlterField(
            model_name='residencephoto',
            name='image',
            field=models.ImageField(upload_to='residence_photos/', validators=[core.models.validate_image]),
        ),
    ]
