# Generated by Django 5.0.14 on 2026-07-04 04:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_residence_viewers_alter_residence_house_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='fraud_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='residence',
            name='image_quality_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='residence',
            name='image_quality_status',
            field=models.CharField(choices=[('unchecked', 'Unchecked'), ('passed', 'Passed'), ('failed', 'Failed')], default='unchecked', max_length=20),
        ),
        migrations.AddField(
            model_name='residence',
            name='suspected_fraud',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='residencephoto',
            name='image',
            field=models.ImageField(upload_to='residence_photos/', validators=[core.models.validate_image]),
        ),
    ]
