# Generated by Django 6.0.6 on 2026-07-04 04:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_residence_fraud_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='county',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='residencephoto',
            name='image',
            field=models.ImageField(upload_to='residence_photos/', validators=[core.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='roommateprofile',
            name='preferred_county',
            field=models.CharField(max_length=100),
        ),
    ]
