# Generated by Django 6.0.6 on 2026-07-04 05:04

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_residence_county_alter_residencephoto_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='boost_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residence',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residence',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residence',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='residencephoto',
            name='image',
            field=models.ImageField(upload_to='residence_photos/', validators=[core.models.validate_image]),
        ),
    ]
