# Generated by Django 6.0.6 on 2026-07-10 12:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_profile_is_suspended_alter_residencephoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='residence',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='residence',
            name='front_image',
            field=models.ImageField(null=True, upload_to='residences/fronts/'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='landmark',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='residence',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='residence',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='residence',
            name='nearby_hospital',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='residence',
            name='nearby_school',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='residence',
            name='nearest_stage',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='residence',
            name='rent_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='residence',
            name='vacancy_poster',
            field=models.ImageField(null=True, upload_to='residences/posters/'),
        ),
        migrations.AlterField(
            model_name='residencephoto',
            name='image',
            field=models.ImageField(upload_to='residence_photos/', validators=[core.models.validate_image]),
        ),
    ]
