# Generated by Django 6.0.6 on 2026-07-13 06:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_residencephoto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniturevendor',
            name='is_major_sponsor',
            field=models.BooleanField(default=False, help_text='Shows on every listing page, regardless of location'),
        ),
        migrations.AddField(
            model_name='mover',
            name='is_major_sponsor',
            field=models.BooleanField(default=False, help_text='Shows on every listing page, regardless of location'),
        ),
        migrations.AlterField(
            model_name='residencephoto',
            name='image',
            field=models.ImageField(upload_to='residence_photos/', validators=[core.models.validate_image]),
        ),
    ]
