# Generated by Django 6.0.6 on 2026-07-13 06:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_furniturevendor_is_major_sponsor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniturevendor',
            name='service_counties',
            field=models.CharField(blank=True, help_text='Comma-separated counties served, e.g. Nairobi, Kiambu', max_length=500),
        ),
        migrations.AddField(
            model_name='mover',
            name='service_counties',
            field=models.CharField(blank=True, help_text='Comma-separated counties served, e.g. Nairobi, Kiambu', max_length=500),
        ),
        migrations.AlterField(
            model_name='residencephoto',
            name='image',
            field=models.ImageField(upload_to='residence_photos/', validators=[core.models.validate_image]),
        ),
    ]
