# Generated by Django 6.0.6 on 2026-07-15 19:35

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_residencephoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencephoto',
            name='image',
            field=models.ImageField(upload_to='residence_photos/', validators=[core.models.validate_image]),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('tier', models.CharField(choices=[('sponsored', 'Sponsored'), ('partner', 'Location Partner'), ('directory', 'Directory Listing')], max_length=20)),
                ('category', models.CharField(choices=[('movers', 'Movers'), ('furniture', 'Furniture')], max_length=20)),
                ('service_areas', models.CharField(help_text="Comma-separated town names, lowercase, no spaces e.g. 'juja,thika'", max_length=300)),
                ('website_url', models.URLField()),
                ('description', models.TextField(blank=True, max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendor_logos/')),
                ('data_source', models.CharField(choices=[('scraped', 'Scraped'), ('manual', 'Manual'), ('mixed', 'Mixed')], default='manual', max_length=10)),
                ('scrape_config', models.JSONField(blank=True, help_text="e.g. {'product_page_url': 'https://vendor.com/shop', 'item_selector': '.product-card', 'name_selector': '.product-title', 'price_selector': '.price', 'image_selector': 'img'}", null=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('scrape_status', models.CharField(choices=[('ok', 'OK'), ('failed', 'Failed'), ('never_run', 'Never Run')], default='never_run', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'tier', 'is_active'], name='core_vendor_categor_2c9c1f_idx')],
            },
        ),
    ]
