# Generated by Django 6.0.6 on 2026-07-15 20:12

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_residencephoto_image_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('source', models.CharField(choices=[('scraped', 'Scraped'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoverProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('source', models.CharField(choices=[('scraped', 'Scraped'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='vendor',
            name='core_vendor_categor_2c9c1f_idx',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.AddField(
            model_name='furniturevendor',
            name='data_source',
            field=models.CharField(choices=[('scraped', 'Scraped'), ('manual', 'Manual'), ('mixed', 'Mixed')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='furniturevendor',
            name='last_scraped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='furniturevendor',
            name='scrape_config',
            field=models.JSONField(blank=True, help_text="e.g. {'product_page_url': 'https://vendor.com/shop', 'item_selector': '.product-card', 'name_selector': '.product-title', 'price_selector': '.price', 'image_selector': 'img'}", null=True),
        ),
        migrations.AddField(
            model_name='furniturevendor',
            name='scrape_status',
            field=models.CharField(choices=[('ok', 'OK'), ('failed', 'Failed'), ('never_run', 'Never Run')], default='never_run', max_length=10),
        ),
        migrations.AddField(
            model_name='mover',
            name='data_source',
            field=models.CharField(choices=[('scraped', 'Scraped'), ('manual', 'Manual'), ('mixed', 'Mixed')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='mover',
            name='last_scraped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mover',
            name='scrape_config',
            field=models.JSONField(blank=True, help_text="e.g. {'product_page_url': 'https://vendor.com/shop', 'item_selector': '.product-card', 'name_selector': '.product-title', 'price_selector': '.price', 'image_selector': 'img'}", null=True),
        ),
        migrations.AddField(
            model_name='mover',
            name='scrape_status',
            field=models.CharField(choices=[('ok', 'OK'), ('failed', 'Failed'), ('never_run', 'Never Run')], default='never_run', max_length=10),
        ),
        migrations.AlterField(
            model_name='residencephoto',
            name='image',
            field=models.ImageField(upload_to='residence_photos/', validators=[core.models.validate_image]),
        ),
        migrations.AddField(
            model_name='furnitureproduct',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.furniturevendor'),
        ),
        migrations.AddField(
            model_name='moverproduct',
            name='mover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.mover'),
        ),
        migrations.AddIndex(
            model_name='furnitureproduct',
            index=models.Index(fields=['vendor', 'is_active'], name='core_furnit_vendor__98ac7b_idx'),
        ),
        migrations.AddIndex(
            model_name='moverproduct',
            index=models.Index(fields=['mover', 'is_active'], name='core_moverp_mover_i_d5f014_idx'),
        ),
    ]
