# Generated by Django 6.0.6 on 2026-07-16 12:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_residencephoto_image_furnituregalleryimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mover',
            name='contract_expires_at',
            field=models.DateField(blank=True, help_text='Sponsorship/listing contract end date', null=True),
        ),
        migrations.AlterField(
            model_name='residencephoto',
            name='image',
            field=models.ImageField(upload_to='residence_photos/', validators=[core.models.validate_image]),
        ),
    ]
