# Generated by Django 6.0.6 on 2026-07-16 16:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_mover_contract_expires_at_alter_residencephoto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniturevendor',
            name='contract_end_date',
            field=models.DateField(blank=True, help_text="When this mover's paid listing/contract expires", null=True),
        ),
        migrations.AlterField(
            model_name='residencephoto',
            name='image',
            field=models.ImageField(upload_to='residence_photos/', validators=[core.models.validate_image]),
        ),
    ]
