# Generated by Django 6.0.6 on 2026-07-22 09:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_residencephoto_image_listingagreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniturevendor',
            name='category',
            field=models.CharField(choices=[('furniture', 'Furniture'), ('curtains', 'Curtains'), ('electronics', 'Electronics'), ('kitchen', 'Kitchen'), ('mattresses', 'Mattresses'), ('bathroom', 'Bathroom'), ('cleaning', 'Cleaning'), ('lighting', 'Lighting'), ('repairs', 'Repairs'), ('garden', 'Garden')], default='furniture', max_length=20),
        ),
        migrations.AlterField(
            model_name='residencephoto',
            name='image',
            field=models.ImageField(upload_to='residence_photos/', validators=[core.models.validate_image]),
        ),
    ]
