# Generated by Django 6.0.6 on 2026-07-22 10:11

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_furniturevendor_category_alter_residencephoto_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mover',
            name='closed_weekdays',
            field=models.CharField(blank=True, help_text="Comma-separated, 0=Mon..6=Sun, e.g. '6' for closed Sundays", max_length=20),
        ),
        migrations.AddField(
            model_name='mover',
            name='closes_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mover',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='mover',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='mover',
            name='opens_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='residencephoto',
            name='image',
            field=models.ImageField(upload_to='residence_photos/', validators=[core.models.validate_image]),
        ),
        migrations.CreateModel(
            name='FurnitureVendorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.furniturevendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('vendor', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MoverReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.mover')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('mover', 'user')},
            },
        ),
    ]
