# Generated by Django 6.0.6 on 2026-07-24 11:37

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_profile_settings_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='compact_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='hide_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hide_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='reduce_motion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme_preference',
            field=models.CharField(choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=6),
        ),
        migrations.AlterField(
            model_name='residencephoto',
            name='image',
            field=models.ImageField(upload_to='residence_photos/', validators=[core.models.validate_image]),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('favourite_residence_updates', models.BooleanField(default=True)),
                ('new_inquiry_alerts', models.BooleanField(default=True)),
                ('new_review_alerts', models.BooleanField(default=True)),
                ('newsletter', models.BooleanField(default=True)),
                ('marketing_emails', models.BooleanField(default=False)),
                ('notification_sounds', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
