# Generated by Django 6.0.6 on 2026-08-08 20:31

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_residencephoto_image_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('emergency', 'Emergency / Safety Concern'), ('scam', 'Suspected Scam or Fraud'), ('harassment', 'Harassment or Abusive Behavior'), ('payment', 'Payment / M-Pesa Issue'), ('login', 'Login / Sign-in Problem'), ('account_access', 'Account Locked or Suspended'), ('verification', 'ID or Business Verification Issue'), ('listing_delay', 'Listing Not Approved / Not Going Live'), ('listing_edit', "Listing Info Wrong or Won't Update"), ('notifications', 'Notifications Not Working'), ('messaging', 'Chat / Messaging Problem'), ('bug', 'Bug or Technical Issue'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='residencephoto',
            name='image',
            field=models.ImageField(upload_to='residence_photos/', validators=[core.models.validate_image]),
        ),
    ]
