# Generated by Django 6.0.6 on 2026-08-09 11:45

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_residentagreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resident_role',
            field=models.CharField(blank=True, choices=[('normal', 'Normal / Renter'), ('landlord', 'Landlord'), ('agent', 'Agent'), ('caretaker', 'Caretaker')], help_text='Only meaningful when account_type is resident.', max_length=10),
        ),
        migrations.AlterField(
            model_name='residencephoto',
            name='image',
            field=models.ImageField(upload_to='residence_photos/', validators=[core.models.validate_image]),
        ),
    ]
