# Generated by Django 6.0.6 on 2026-08-09 12:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_profile_resident_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentagreement',
            name='role',
            field=models.CharField(blank=True, choices=[('normal', 'Normal / Renter'), ('landlord', 'Landlord'), ('agent', 'Agent'), ('caretaker', 'Caretaker')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hide_phone',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='residencephoto',
            name='image',
            field=models.ImageField(upload_to='residence_photos/', validators=[core.models.validate_image]),
        ),
    ]
