# Generated by Django 6.0.6 on 2026-08-09 13:38

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_residencephoto_image_residencesponsorship'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accent_color',
            field=models.CharField(choices=[('teal', 'Teal'), ('blue', 'Blue'), ('purple', 'Purple'), ('green', 'Green'), ('rose', 'Rose'), ('orange', 'Orange')], default='teal', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=6),
        ),
        migrations.AlterField(
            model_name='residencephoto',
            name='image',
            field=models.ImageField(upload_to='residence_photos/', validators=[core.models.validate_image]),
        ),
    ]
