# Generated by Django 6.0.6 on 2026-08-10 15:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_profile_followers_count_profile_following_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencephoto',
            name='image',
            field=models.ImageField(upload_to='residence_photos/', validators=[core.models.validate_image]),
        ),
    ]
