# Generated by Django 6.0.6 on 2026-07-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_business_settings_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspayment',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='businesspayment',
            name='merchant_request_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='businesspayment',
            name='mpesa_receipt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='businesspayment',
            name='plan',
            field=models.CharField(blank=True, choices=[('starter', 'Starter (Free)'), ('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], help_text='Plan to activate on successful payment', max_length=20),
        ),
    ]
