from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_business_settings_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(
                choices=[
                    ('movers', 'Movers'), ('furniture', 'Furniture Store'),
                    ('curtains', 'Curtains & Blinds'), ('electronics', 'Electronics & Appliances'),
                    ('kitchen', 'Kitchen & Home Fittings'), ('mattresses', 'Mattresses & Bedding'),
                    ('bathroom', 'Bathroom & Sanitary'), ('cleaning', 'Cleaning Services'),
                    ('lighting', 'Lighting'), ('repairs', 'Repairs & Maintenance'),
                    ('garden', 'Garden & Landscaping'), ('internet', 'Internet Providers'),
                    ('security', 'Security Companies'), ('househelp', 'Househelp & Domestic Staff'),
                    ('carpets', 'Carpets & Rugs'), ('bedding', 'Duvets & Blankets'),
                    ('sofas', 'Sofa Shops'), ('beds', 'Bed Stores'), ('wardrobes', 'Wardrobes'),
                    ('dining_furniture', 'Dining Tables'), ('tv_stands', 'TV Stands'),
                    ('office_furniture', 'Office Furniture'), ('interior_design', 'Interior Designers'),
                    ('home_decor', 'Home Decorators'), ('blinds', 'Blinds'), ('rugs', 'Rugs'),
                    ('wood_flooring', 'Wooden Flooring'), ('tiles', 'Tiles'),
                    ('vinyl_flooring', 'Vinyl Flooring'), ('tv_sound', 'TVs & Sound Systems'),
                    ('fridges', 'Refrigerators'), ('washing_machines', 'Washing Machines'),
                    ('cookers', 'Cookers'), ('microwaves', 'Microwaves'),
                    ('water_dispensers', 'Water Dispensers'), ('air_conditioning', 'Air Conditioners'),
                    ('fans', 'Fans'), ('smart_devices', 'Smart Home Devices'),
                    ('kitchen_utensils', 'Kitchen Utensils'), ('cookware', 'Cookware'),
                    ('tableware', 'Plates & Cutlery'), ('kitchen_cabinets', 'Kitchen Cabinets'),
                    ('kitchen_design', 'Modular Kitchens'), ('shower_installation', 'Shower Installation'),
                    ('water_heaters', 'Water Heaters'), ('bathroom_fittings', 'Bathroom Fittings'),
                    ('sanitaryware', 'Toilets & Basins'), ('mirrors', 'Mirrors'),
                    ('electricians', 'Electricians'), ('led_lighting', 'LED Lighting'),
                    ('chandeliers', 'Chandeliers'), ('ceiling_lights', 'Ceiling Lights'),
                    ('outdoor_lighting', 'Outdoor Lights'), ('smart_lighting', 'Smart Lighting'),
                    ('switches_sockets', 'Switches & Sockets'), ('solar_systems', 'Solar Systems'),
                    ('backup_power', 'Backup Power'), ('plumbers', 'Plumbers'),
                    ('boreholes', 'Borehole Companies'), ('water_delivery', 'Water Delivery'),
                    ('water_tanks', 'Water Tanks'), ('water_filters', 'Water Filters'),
                    ('pumps', 'Pumps'), ('drainage', 'Drainage'),
                    ('cctv_installers', 'CCTV Installers'), ('alarm_systems', 'Alarm Systems'),
                    ('electric_fencing', 'Electric Fences'), ('smart_locks', 'Smart Locks'),
                    ('door_access', 'Door Access Systems'), ('wifi_installation', 'Wi-Fi Installation'),
                    ('starlink', 'Starlink Installation'), ('networking', 'Networking Companies'),
                    ('smart_automation', 'Smart Home Automation'), ('packers', 'Packers'),
                    ('storage_companies', 'Storage Companies'), ('warehouses', 'Warehouses'),
                    ('move_cleaning', 'Cleaning After Moving'), ('truck_hire', 'Truck Hire'),
                    ('painters', 'Painters'), ('welders', 'Welders'), ('carpenters', 'Carpenters'),
                    ('contractors', 'Contractors'), ('masonry', 'Masonry'), ('roofing', 'Roofing'),
                    ('ceiling_installers', 'Ceiling Installers'), ('aluminium_windows', 'Aluminium Windows'),
                    ('glass_installers', 'Glass Installers'), ('gate_fabricators', 'Gate Fabricators'),
                    ('landscaping', 'Landscaping'), ('tree_cutting', 'Tree Cutting'),
                    ('lawn_maintenance', 'Lawn Maintenance'), ('pool_maintenance', 'Pool Maintenance'),
                    ('laundry', 'Laundry'), ('pest_control', 'Pest Control'),
                    ('garbage_collection', 'Garbage Collection'), ('nannies', 'Nannies'),
                    ('caregivers', 'Caregivers'), ('babysitters', 'Babysitters'),
                    ('private_chefs', 'Private Chefs'), ('laundry_pickup', 'Laundry Pickup'),
                    ('saccos', 'SACCOs'), ('mortgage_providers', 'Mortgage Providers'),
                    ('home_insurance', 'Home Insurance'), ('banks', 'Banks'), ('valuers', 'Valuers'),
                    ('pet_grooming', 'Pet Grooming'), ('vet_clinics', 'Veterinary Clinics'),
                    ('pet_stores', 'Pet Stores'), ('dog_walkers', 'Dog Walkers'),
                    ('smart_cameras', 'Smart Cameras'), ('smart_sensors', 'Smart Sensors'),
                    ('smart_thermostats', 'Smart Thermostats'), ('home_automation', 'Home Automation'),
                    ('other', 'Other'),
                ],
                default='other',
                max_length=20,
            ),
        ),
    ]