# Generated by Django 6.0.6 on 2026-07-27 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_businesspayment_checkout_request_id_and_more'),
        ('business', '0004_expand_categories'),
    ]

    operations = [
    ]
