# Generated by Django 6.0.6 on 2026-07-28 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_coupons_promotions'),
        ('business', '0005_merge_20260727_1611'),
    ]

    operations = [
    ]
