# Generated by Django 6.0.6 on 2026-07-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_merge_20260728_1250'),
        ('business', '0006_services_bookings'),
    ]

    operations = [
    ]
