# Generated by Django 6.0.6 on 2026-07-28 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_merge_0006_merge_20260728_1250_0006_services_bookings'),
        ('business', '0007_quotations_orders'),
    ]

    operations = [
    ]
