# Generated by Django 6.0.6 on 2026-07-28 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_business_ai_usage'),
        ('business', '0008_merge_20260728_1311'),
    ]

    operations = [
    ]
