# Generated by Django 6.0.6 on 2026-07-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_business_branch'),
        ('business', '0009_merge_0008_business_ai_usage_0008_merge_20260728_1311'),
    ]

    operations = [
    ]
